// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vstqtcvwnvkcdrxteubg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzdHF0Y3Z3bnZrY2RyeHRldWJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTk0NDcsImV4cCI6MjA1OTA5NTQ0N30.NdXDXoEyNmW309tSXCTiFu_MPmpP1TrD0FKPgf-nK2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);